// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syamxswsyylzvvcdmpjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5YW14c3dzeXlsenZ2Y2RtcGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzAwODgsImV4cCI6MjA2NDU0NjA4OH0.NahrbwV-cv4uKbygo1aCLNnnMeBqj_kvyPuVn7sZ-g8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);